### PR TITLE
fix random await crash

### PR DESCRIPTION
**Pull request by ghost**
#1

### CODE REVIEW

**Comment by CodingCellist** [comment]
Hey, sorry for taking so long to get back. This approach looks fine to me, and I believe it is fine in terms of how one should use CVs (test a value, then wait on the CV if the value was `False`, or not there in this case).

I can't help but wonder if we should remove the `assert_total` call, since `await` (afaiu) is by definition not total: It is not guaranteed to reduce the size of the channel, nor is it guaranteed to make some sort of progress... :thinking:

**Comment by ghost** [comment]
I've actually just used my own implementation for buffered channel for my project because I came up with a simpler approach to this problem. Rather than using Conditions and IORef, I just used channels directly to receive data in a blocking manner. What do you think of it?

My implementation is here: https://github.com/octeep/idris2-http/blob/master/src/Utils/Queue.idr

**Comment by CodingCellist** [comment]
I think it's cool! My only concern is that, afaiu, mutexes are designed for exclusive access to a resource as opposed to "hey I'm done with this, someone else can have it"-signalling, which is what you (probably?) want with a queue. I believe condition variables also suspend the thread(s) on `condition_wait`, which means you don't waste CPU running a spin-lock kinda thing, so they're more resource efficient (don't know if that's an actual concern, i.e. it happens and affects things, or an idealised concern though).

I'm not 100% sure I entirely understand it, but when I was implementing this ~6months ago, these SO answers helped convince me that there must be something to it :sweat_smile: :
- https://stackoverflow.com/questions/12551341/when-is-a-condition-variable-needed-isnt-a-mutex-enough
- https://stackoverflow.com/questions/3513045/conditional-variable-vs-semaphore

**Comment by ghost** [comment]
> mutexes are designed for exclusive access to a resource. 

> "hey I'm done with this, someone else can have it"-signalling

Aren't they the same? In this case, the resource is the `IORef`. The mutex is supposed to prevent other threads from reading / writing it while on thread is doing the read/write, so as to prevent a race condition. It is essentially `mutex_unlock` essentially is just telling other threads that the current occupying thread is done with the `IORef`, and another thread can have it.

Also I can't seem to find any resources on condition wait being more efficient than mutex locking. I assume it's just kernel magic and not really something that we can know. 

Edit: I just read the second SO that you sent. I think what the author meant is that condition is used as a replacement for a spinlock (essentially a while loop that checks for a condition, and sleep for x amount of time if it fails). This does not imply that it outperforms mutex. 

Also condition isn't really "hey I'm done with this, someone else can have it", but rather "whoever is waiting for x to happen, check if x has happened and move on, or keep waiting for another notice" (sorry for my poor analogy). It's to replace codes like
```c
while(flag) {
   sleep(1);
}
do_something_else()
```
with 
```c
while(flag) {
   condition_wait();
}
do_something_else()
```
So rather than sleeping for a second in a loop (spinlock), it would just wait for someone to notify the condition, thus saving time and resources consumption. It's not really applicable in my use case, where I simply want to prevent other threads from accessing the `IORef` while one thread is already accessing it.

**Pull request merged**
